/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


/**
 * @class
 * Initializes a new instance of the PolicyModel class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {date} [created]
 * 
 * @member {string} [name]
 * 
 * @member {string} [systemName]
 * 
 * @member {string} [typeName]
 * 
 * @member {array} [policies]
 * 
 */
export interface PolicyModel {
    id?: number;
    created?: Date;
    name?: string;
    systemName?: string;
    typeName?: string;
    policies?: Policy[];
}

/**
 * @class
 * Initializes a new instance of the Policy class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {number} [policyModelId]
 * 
 * @member {date} [created]
 * 
 * @member {string} [name]
 * 
 * @member {object} [policyModel]
 * 
 * @member {number} [policyModel.id]
 * 
 * @member {date} [policyModel.created]
 * 
 * @member {string} [policyModel.name]
 * 
 * @member {string} [policyModel.systemName]
 * 
 * @member {string} [policyModel.typeName]
 * 
 * @member {array} [policyModel.policies]
 * 
 * @member {array} [policyVersions]
 * 
 */
export interface Policy {
    id?: number;
    policyModelId?: number;
    created?: Date;
    name?: string;
    policyModel?: PolicyModel;
    policyVersions?: PolicyVersion[];
}

/**
 * @class
 * Initializes a new instance of the PolicyVersion class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {number} [policyId]
 * 
 * @member {date} [created]
 * 
 * @member {object} [policy]
 * 
 * @member {number} [policy.id]
 * 
 * @member {number} [policy.policyModelId]
 * 
 * @member {date} [policy.created]
 * 
 * @member {string} [policy.name]
 * 
 * @member {object} [policy.policyModel]
 * 
 * @member {number} [policy.policyModel.id]
 * 
 * @member {date} [policy.policyModel.created]
 * 
 * @member {string} [policy.policyModel.name]
 * 
 * @member {string} [policy.policyModel.systemName]
 * 
 * @member {string} [policy.policyModel.typeName]
 * 
 * @member {array} [policy.policyModel.policies]
 * 
 * @member {array} [policy.policyVersions]
 * 
 * @member {array} [policyRules]
 * 
 */
export interface PolicyVersion {
    id?: number;
    policyId?: number;
    created?: Date;
    policy?: Policy;
    policyRules?: PolicyRule[];
}

/**
 * @class
 * Initializes a new instance of the PolicyRule class.
 * @constructor
 * @member {number} [policyVersionId]
 * 
 * @member {date} [created]
 * 
 * @member {number} [order]
 * 
 * @member {string} [condition]
 * 
 * @member {string} [value]
 * 
 * @member {object} [policyVersion]
 * 
 * @member {number} [policyVersion.id]
 * 
 * @member {number} [policyVersion.policyId]
 * 
 * @member {date} [policyVersion.created]
 * 
 * @member {object} [policyVersion.policy]
 * 
 * @member {number} [policyVersion.policy.id]
 * 
 * @member {number} [policyVersion.policy.policyModelId]
 * 
 * @member {date} [policyVersion.policy.created]
 * 
 * @member {string} [policyVersion.policy.name]
 * 
 * @member {object} [policyVersion.policy.policyModel]
 * 
 * @member {number} [policyVersion.policy.policyModel.id]
 * 
 * @member {date} [policyVersion.policy.policyModel.created]
 * 
 * @member {string} [policyVersion.policy.policyModel.name]
 * 
 * @member {string} [policyVersion.policy.policyModel.systemName]
 * 
 * @member {string} [policyVersion.policy.policyModel.typeName]
 * 
 * @member {array} [policyVersion.policy.policyModel.policies]
 * 
 * @member {array} [policyVersion.policy.policyVersions]
 * 
 * @member {array} [policyVersion.policyRules]
 * 
 */
export interface PolicyRule {
    policyVersionId?: number;
    created?: Date;
    order?: number;
    condition?: string;
    value?: string;
    policyVersion?: PolicyVersion;
}
